[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
os_info = "3"
reqwest = "0.11.22"
flate2 = "1.0.28"
tokio = { version = "1", features = ["full"] }
tar = "0.4.40"
inquire = "0.6.2"
toml = "0.8.2"
dirs = "5.0"
nix = { version = "0.27.1", features = ["signal"] }
colored = "2"
