name: Release

on:
  push:
    tags:
      - '*'

env:
  APP_NAME: 'mycelial'
  MAINTAINER: 'knowthen'
  DESC: 'mycelial cli bootstraps the Mycelial binaries'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    env:
      RUSTFLAGS: "-C target-feature=-crt-static"
      CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER: arm-linux-gnueabihf-gcc
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      OPENSSL_VERSION: 1.1.1w
      OPENSSL_PREFIX: /tmp/openssl/

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu

          - build: linux
            os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu

          - build: linux
            os: ubuntu-20.04
            target: arm-unknown-linux-gnueabihf

          - build: macos
            os: macos-12
            target: x86_64-apple-darwin

          - build: macos
            os: macos-12
            target: aarch64-apple-darwin

    steps:
      - name: checkout
        uses: actions/checkout@v3          

      - name: install packages (linux)
        if: matrix.build == 'linux'
        run: |
          sudo apt update
          sudo apt install pkg-config gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu musl-tools libssl-dev wget ruby-dev build-essential -qy
          sudo gem i fpm -f

      - name: install packages (macos)
        if: matrix.build == 'macos'
        run: |
          brew install openssl
      
      - name: build openssl 
        if: matrix.build == 'linux' && matrix.target != 'x86_64-unknown-linux-gnu'
        run: |
            export CC_PREFIX=`echo ${{ matrix.target }} | sed 's/unknown-//g'`
            mkdir -p $OPENSSL_PREFIX/$OPENSSL_VERSION/
            cd ${OPENSSL_PREFIX}
            wget -nc https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
            tar xvf openssl-$OPENSSL_VERSION.tar.gz
            cd openssl-${OPENSSL_VERSION}
            export CC="$CC_PREFIX-gcc"
            exportCXX="$CC_PREFIX-g++"
            export AS="$CC_PREFIX-as"
            export AR="$CC_PREFIX-ar"
            export NM="$CC_PREFIX-nm"
            export RANLIB="$CC_PREFIX-ranlib"
            export LD="$CC_PREFIX-ld"
            export STRIP="$CC_PREFIX-strip"
            ./Configure linux-generic32 shared \
               --prefix=$OPENSSL_PREFIX/$OPENSSL_VERSION/${{ matrix.target }} \
               --openssldir=$OPENSSL_PREFIX/$OPENSSL_VERSION/${{ matrix.target }}
            make
            make install
            echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX/$OPENSSL_VERSION/${{matrix.target}}/include" >> $GITHUB_ENV
            echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX/$OPENSSL_VERSION/${{matrix.target}}/lib" >> $GITHUB_ENV
            echo "OPENSSL_STATIC=1" >> $GITHUB_ENV

      - name: setup rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: build binary
        run: |
          cargo build --verbose --release --target ${{ matrix.target }}
          ls target/${{ matrix.target }}/release/

      - name: build archive
        if: matrix.build == 'linux'
        run: |
          export MYCELIAL_NAME=mycelial-${{ matrix.target }}.tgz
          tar -czf $MYCELIAL_NAME -C "./target/${{ matrix.target }}/release/" mycelial
          echo "MYCELIAL_NAME=$MYCELIAL_NAME" >> $GITHUB_ENV

      - name: build archive
        if: matrix.build == 'macos'
        run: |
          export MYCELIAL_NAME=mycelial-${{ matrix.target }}.tgz
          tar -czf $MYCELIAL_NAME -C "./target/${{ matrix.target }}/release/" mycelial
          echo "MYCELIAL_NAME=$MYCELIAL_NAME" >> $GITHUB_ENV

      - name: create deb package folder
        if: matrix.build == 'linux'
        run: |
          mkdir -p .debpkg/usr/bin
          cp ./target/${{ matrix.target }}/release/mycelial .debpkg/usr/bin/ 
          ls .debpkg/usr/bin/

      - name: build debian package arm32
        if: matrix.target == 'arm-unknown-linux-gnueabihf'
        uses: jiro4989/build-deb-action@v3
        with:
          package: ${{ env.APP_NAME }}
          package_root: .debpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'armhf'
          desc: '${{ env.DESC }}'

      - name: build debian package arm64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        uses: jiro4989/build-deb-action@v3
        with:
          package: ${{ env.APP_NAME }}
          package_root: .debpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'arm64'
          desc: '${{ env.DESC }}'

      - name: build debian package x86_64
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        uses: jiro4989/build-deb-action@v3
        with:
          package: ${{ env.APP_NAME }}
          package_root: .debpkg
          maintainer: ${{ env.MAINTAINER }}
          version: ${{ github.ref }}
          arch: 'amd64'
          desc: '${{ env.DESC }}'

      - name: build rpm x86_64
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        run: |
          cp ./target/${{ matrix.target }}/release/mycelial ./
          ls
          fpm \
            -s dir -t rpm \
            -p mycelial-${GITHUB_REF#refs/*/}-1.x86_64.rpm \
            --name mycelial \
            --license apache2 \
            --version ${GITHUB_REF#refs/*/} \
            --architecture x86_64 \
            --description "Mycelial CLI" \
            --url "https://mycelial.com" \
            --maintainer "James Moore <james@mycelial.com>" \
            mycelial=/usr/bin/mycelial

      - name: build rpm arm64
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          cp ./target/${{ matrix.target }}/release/mycelial ./
          ls
          fpm \
            -s dir -t rpm \
            -p mycelial-${GITHUB_REF#refs/*/}-1.arm64.rpm \
            --name mycelial \
            --license apache2 \
            --version ${GITHUB_REF#refs/*/} \
            --architecture arm64 \
            --description "Mycelial CLI" \
            --url "https://mycelial.com" \
            --maintainer "James Moore <james@mycelial.com>" \
            mycelial=/usr/bin/mycelial

      - name: build rpm arm
        if: matrix.target == 'arm-unknown-linux-gnueabihf'
        run: |
          cp ./target/${{ matrix.target }}/release/mycelial ./
          ls
          fpm \
            -s dir -t rpm \
            -p mycelial-${GITHUB_REF#refs/*/}-1.armhf.rpm \
            --name mycelial \
            --license apache2 \
            --version ${GITHUB_REF#refs/*/} \
            --architecture armhf \
            --description "Mycelial CLI" \
            --url "https://mycelial.com" \
            --maintainer "James Moore <james@mycelial.com>" \
            mycelial=/usr/bin/mycelial

      - name: release
        if: matrix.build == 'macos'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.MYCELIAL_NAME }}"
          artifactErrorsFailBuild: true
          allowUpdates: true

      - name: release
        if: matrix.build == 'linux'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.MYCELIAL_NAME }}, ./*.deb, ./*.rpm"
          artifactErrorsFailBuild: true
          allowUpdates: true